# Usar una imagen oficial de MySQL
FROM mysql:8.0

# Definir las variables de entorno
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=appdb
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=password

# Exponer el puerto de MySQL
EXPOSE 3306

